### ISSUE TITLE
Cant load thumbnail in Media Library

### ISSUE THREAD

**Issue by hoangnhatfe** [thor9n/strapi-provider-upload-bunnynet#2]
Hi,
I have install your plugin to integrate with bunny.net, but when I upload successfully in library cant load the thumbnail. It quite hard to choose the image in entrie. Please help me to fix this issue.
![Screen Shot 2023-03-09 at 19 03 16](https://user-images.githubusercontent.com/86102501/224018440-0f9e4aa8-1ece-44e7-83f7-d17dda7ea5e7.png)
Thanks,

**Comment by thor9n** [comment]
Did you follow the documentation including:

- setting `BUNNY_PULL_ZONE` to Pull Zone URL without trailing slash (e.g. `https://<pull-zone-name>.b-cdn.net`) and
- [Security Middleware Configuration](https://github.com/thor9n/strapi-provider-upload-bunnynet/#security-middleware-configuration)?

**Comment by santyas** [comment]
> Did you follow the documentation including:
> 
> * setting `BUNNY_PULL_ZONE` to Pull Zone URL without trailing slash (e.g. `https://<pull-zone-name>.b-cdn.net`) and
> * [Security Middleware Configuration](https://github.com/thor9n/strapi-provider-upload-bunnynet/#security-middleware-configuration)?

If my-zone/ has folders should I add before this last one?
