### ISSUE TITLE
Internal server error when try to upload

### ISSUE THREAD

**Issue by santyas** [thor9n/strapi-provider-upload-bunnynet#3]
Hello! I get this terminal error when I try to upload a jpg image:

error: Error uploading to Bunny.net: Request failed with status code 401
   at /projectfolder/node_modules/strapi-provider-upload-bunnynet/lib/index.js:34:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Ive configured plugin and middleware files with the password, storage name and pullzone url without last slash. On localhost or production I get that 401 error on my terminal, and the 500 error on my chrome console. (Im using typescript).

Should I configure something else?
Thank you :)

**Comment by thor9n** [comment]
Hello!

401 means "Unauthorized". Can you please show me the full API call including host, headers and body. Make sure to hide any keys/secrets.

/N

**Comment by thor9n** [comment]
Hello!

401 means "Unauthorized". Can you please show me the full API call including host, headers and body. Make sure to hide any keys/secrets.

/N

**Comment by santyas** [comment]
Hello @thor9n :)

Thank you! Im using this config at plugins.ts:

`
module.exports = ({ env }) => ({
  upload: {
    config: {
      provider: "strapi-provider-upload-bunnynet",
      providerOptions: {
        api_key: env('BUNNY_API_KEY'),
        storage_zone: env('BUNNY_STORAGE_ZONE'),
        pull_zone: env('BUNNY_PULL_ZONE'),
      },
    },
  },
})
`

env variables:
`
BUNNY_API_KEY=PASSWORD(not the Read-only password)
BUNNY_STORAGE_ZONE=zonenameonly
BUNNY_PULL_ZONE=https://mypull.b-cdn.net

`

And in middleware.ts:
`
  'strapi::errors',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", "https://mypull.b-cdn.net"],
          "media-src": ["'self'", "data:", "blob:", "https://mypull.b-cdn.net"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
`

Should I configure something else?

**Comment by thor9n** [comment]
The error indicates it's an authorization error so I thought it was the API_KEY that was wrong – can you please double check it's loaded correctly.

Not in the office now, but 'll double check everything tomorrow morning and get back.

**Comment by santyas** [comment]
I'm pretty sure that I copy and paste the password inside ftp/api section (not the token auth). Also I cant test it inside the api reference example tester :( I get: "Message": "Authorization has been denied for this request."

**Comment by santyas** [comment]
@thor9n well I've chat with support and they've told me I have to use "ny.storage..." bc my server is in US (NY).

I also tried on Insomnia using the url https://ny.storage.bunnycdn.com/storagename/path/ and worked fine :)

How can we reach to this? I edited the baseURL of the bunny_api const and it can upload the image perfectly.

Thank you!

**Comment by thor9n** [comment]
Great – sounds like you solved it?

> How can we reach to this?

Not sure what you mean by this.

**Comment by santyas** [comment]
Hello 
![Captura de Pantalla 2023-06-20 a la(s) 15 59 22](https://github.com/thor9n/strapi-provider-upload-bunnynet/assets/4504608/98d89e94-71c5-41a6-96cd-48a7a146aab7)

I had to modify that url because it is not always https:// storage.bunnycdn ... maybe all that url could be a param to get from env var.

**Comment by thor9n** [comment]
Thanks for catching that @santyas 

I've added a new branch **[storage-endpoint-env-var](https://github.com/thor9n/strapi-provider-upload-bunnynet/tree/storage-endpoint-env-var)** which adds `BUNNY_STORAGE_ENDPOINT` as a environment variable.

Would you mind cloning, testing and confirm it's working as expected?

Cheers!

**Comment by santyas** [comment]
@thor9n oh thank you so much! 

Edited: It works!
