### ISSUE TITLE
How to manage files size (axios) to upload?

### ISSUE THREAD

**Issue by santyas** [thor9n/strapi-provider-upload-bunnynet#6]
Hello! Should be convenient to set maxContentLength + maxBodyLength using custom params? Ive tried to upload a pdf file which sizes +20mb but Ive had to add maxContentLength: Infinity, maxBodyLength: Infinity inside axios create function. Or maybe to get sizeLimit param inside [providerOptions](https://docs.strapi.io/dev-docs/plugins/upload) at plugin file. Thanks!

**Comment by thor9n** [comment]
Sure, that is doable. I don't have time to address it right now, but you are welcome publishing a new branch.

Please make sure that this is something that shouldn't be handled in the Strapi middleware as per: https://docs.strapi.io/dev-docs/plugins/upload#max-file-size

**Comment by santyas** [comment]
Sure, let me try. Thank you
