### ISSUE TITLE
Internal server error while attempting to upload assets

### ISSUE THREAD

**Issue by ckshen8** [thor9n/strapi-provider-upload-bunnynet#7]
Internal server error while attempting to upload assets.  I added the following to config/plugins.js.  What does internal server error mean in this case?  Is there any log where I can trace the error?   Thanks!

upload: {
    config: {
      provider: "strapi-provider-upload-bunnynet",
      providerOptions: {
        api_key: env('BUNNY_API_KEY', 'the api key from ftp/ssh section of bunny storage zone'),
        storage_zone: env('BUNNY_STORAGE_ZONE', 'name of storage zone'),
        pull_zone: env('BUNNY_PULL_ZONE', 'bunny pull zone URL without trailing /'),
      },
    },
  },

**Comment by pierrehrt** [comment]
I have me too an error when I'm trying to upload images, I'm stuck on this for a few days already, the documentation is very poor with this plugin:

[2023-08-09 00:47:34.193] error: Error uploading to Bunny.net: Request failed with status code 401
Error: Error uploading to Bunny.net: Request failed with status code 401
    at /Users/pierre/Local/Strapi/be_fit_with_jess_strapi/node_modules/strapi-provider-upload-bunnynet/lib/index.js:34:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by thor9n** [comment]
> I have me too an error when I'm trying to upload images, I'm stuck on this for a few days already, the documentation is very poor with this plugin:
> 
> [2023-08-09 00:47:34.193] error: Error uploading to Bunny.net: Request failed with status code 401
> Error: Error uploading to Bunny.net: Request failed with status code 401
>     at /Users/pierre/Local/Strapi/be_fit_with_jess_strapi/node_modules/strapi-provider-upload-bunnynet/lib/index.js:34:18
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     
>      


Hi Pierre,

The documentation is sufficient: it's a simple plugin for a simple API.

May I suggest that you actually READ the documentation for Bunny.net? https://support.bunny.net/hc/en-us/articles/360024887131-Typical-HTTP-Response-Codes

```
401 Unauthorized

The request requires authentication to access the resource, and the client did not send any credentials, or the credentials that were sent are wrong.
```

Good luck

**Comment by thor9n** [comment]
> I have me too an error when I'm trying to upload images, I'm stuck on this for a few days already, the documentation is very poor with this plugin:
> 
> [2023-08-09 00:47:34.193] error: Error uploading to Bunny.net: Request failed with status code 401
> Error: Error uploading to Bunny.net: Request failed with status code 401
>     at /Users/pierre/Local/Strapi/be_fit_with_jess_strapi/node_modules/strapi-provider-upload-bunnynet/lib/index.js:34:18
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     
>      

> I have me too an error when I'm trying to upload images, I'm stuck on this for a few days already, the documentation is very poor with this plugin:
> 
> [2023-08-09 00:47:34.193] error: Error uploading to Bunny.net: Request failed with status code 401
> Error: Error uploading to Bunny.net: Request failed with status code 401
>     at /Users/pierre/Local/Strapi/be_fit_with_jess_strapi/node_modules/strapi-provider-upload-bunnynet/lib/index.js:34:18
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     
>      


Hi Pierre,

I believe documentation is sufficient: it's a simple plugin for a simple API.

May I suggest that you actually read the documentation for Bunny.net? https://support.bunny.net/hc/en-us/articles/360024887131-Typical-HTTP-Response-Codes

```
401 Unauthorized

The request requires authentication to access the resource, and the client did not send any credentials, or the credentials that were sent are wrong.
```

Have you made sure that the API key are set in your .env file and referenced correctly as stated in documentation and on https://docs.strapi.io/dev-docs/configurations/plugins ?

**Comment by thor9n** [comment]
Hello!

As stated in [Bunny.net's documentation](https://support.bunny.net/hc/en-us/articles/360024887131-Typical-HTTP-Response-Codes):

`401 Unauthorized: The request requires authentication to access the resource, and the client did not send any credentials, or the credentials that were sent are wrong`

The API key should be set in your .env files and plugin configuration as stated on our documentation. I would guess that the API key is not configured, or the wrong API key is configured.

Hope this help you debug.

**Comment by pierrehrt** [comment]
I really check everything 3-4 times, I can't figure out what's wrong/missing.

**here is my plugin.js:**

```
module.exports = ({ env }) => ({
 
  upload: {
    config: {
      
      provider: "strapi-provider-upload-bunnynet",
      providerOptions: {
        region: env("BUNNY_HOST"),
        api_key: env("BUNNY_API_KEY"),
        storage_zone: env("BUNNY_STORAGE_ZONE"),
        pull_zone: env("BUNNY_PULL_ZONE"),
        storage_endpoint: env("BUNNY_STORAGE_ZONE"),
      },
      'duplicate-button': true,
      
    },
    actionOptions: {
      upload: {},
      delete: {},
    },
  },

})
```

 **my .env:**

```
BUNNY_API_KEY=(I took the password of storage zone as shown in the documentation)
BUNNY_STORAGE_ZONE=storage-zone-name
BUNNY_PULL_ZONE=https://pull-zone-name.b-cdn.net
BUNNY_HOST=sg.storage.bunnycdn.com
```

**my middlewares.js:**

```
module.exports = [

  'strapi::errors',
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", "https://pull-zone-name.b-cdn.net"],
          "media-src": ["'self'", "data:", "blob:", "https://pull-zone-name.b-cdn.net"],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
```


All my variables in .env are inserted in my server's local variable. I doublecheck 3 times.

any idea where is the issue?

**Comment by thor9n** [comment]
> BUNNY_API_KEY=(I took the password of storage zone as shown in the documentation)

Are you sure the API key is correct? Their documentation doesn't say that you should take the 'password of the storage zone', but rather the API key found in settings

[See this link](https://support.bunny.net/hc/en-us/articles/360012168840-Where-do-I-find-my-API-key-) and please check if that helps with your problem.

If the problem persists, please log the axios API request by adding the following code to the plugin. You can just temporarily change the `index.js` file in your local `node_modules` folder. Then you paste the code here.
```js
axios.interceptors.request.use(request => {
  console.log('Starting Request', JSON.stringify(request, null, 2))
  return request
})

```

**Comment by pierrehrt** [comment]
Thank you very much, I can't test it right now I will let you know tonight if it solve my problem.

I took the password of the storage zone as shown in the documentation because I saw this on your GitHub repo README:

![Screenshot 2023-08-09 at 15 49 10](https://github.com/thor9n/strapi-provider-upload-bunnynet/assets/91760059/0c6d89dc-2f52-4e66-a9bd-d138f0935895)
